#!/bin/sh

case $1 in
    --publish)
        exec spacetime publish noot
        ;;
    *)
        VERB=$1
        if [ ! -z "$VERB" ]; then
            shift
            exec spacetime $VERB noot "$@"
        fi
        exec spacetime
        ;;
esac